### ISSUE TITLE
[Bug]: Hardened ArgoCD image shows Out-of-sync bug

### ISSUE THREAD

**Issue by rinkydevi** [rapidfort/community-images#618] opened 2024-05-21 09:11 UTC
### Name and Version

rapidfort/argocd:latest

### Which runtime are you using to reproduce this issue?

- [X] Kubernetes
- [ ] Docker Compose
- [ ] Docker

### Is this issue reproducible on the original source image?

Reproducible

### What steps will reproduce the bug?

Run a K8s cluster on your machine and deploy an application to check, here I have made
use of the Minikube and use the sample app in this repo:
“https://gitlab.com/nanuchi/argocd-app-config”
After this we just integrate our app with ArgoCD.

### Are you using any custom parameters or values?

We have used the sample application from the repo [“https://gitlab.com/nanuchi/argocd-app-config”](“https://gitlab.com/nanuchi/argocd-app-config”)

### What is the expected behavior?

It must show the app as SYNCED
![image](https://github.com/rapidfort/community-images/assets/82359874/4a414d53-034a-4bbb-9890-8583c9f3ebff)

### What do you see instead?

It showed app to be OUT OF SYNC
![image](https://github.com/rapidfort/community-images/assets/82359874/6ddbedec-d0d0-4710-be75-40df8c7069fb)

### Additional information

After installing Minikube
1. kubectl port-forward service/rf-argocd-server -n default 8080:443
2. kubectl -n default get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d (to login)

Then to run our application we need to define the namespace argocd:
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

Create files app.yml, dev.yml, svc.yml
Then run kubectl apply -f application.yml

Then open the UI dashboard of argocd, and create our application add the repo url, enable auto sync and then enter path as ”dev”.
This will start to show our app in dashboard and now you can reproduce the issue

**Comment by Kirandeep-Singh-Khehra** [comment] 2024-05-21 14:01
Hi @rinkydevi, there could be many reasons of app being out of sync. It can be caused by a failure or delay taken by minikube or any k8s runtime that you are running. But i can observe that health and initial sync status is good. IMO: This must be an expected behaviour as Sync have worked once. and can you also provide more info on where you applied the changes to add rapidfort's argocd image.

**Comment by rinkydevi** [comment] 2024-05-21 14:45
[](url)Greetings @Kirandeep-Singh-Khehra , it can be a pretty common issue but even after trying to sync with app again it still says the same even though the app is healthy, and same issue when trying to hard refresh and also this problem doesn't arise when working with official argocd [provided recording](
https://github.com/rapidfort/community-images/assets/82359874/e7566ce4-1977-45e1-8d5e-fdc8778c581d
)

**Comment by Kirandeep-Singh-Khehra** [comment] 2024-05-21 15:47
@rinkydevi Unfortunately its not the case on my end.
![image](https://github.com/rapidfort/community-images/assets/107160937/d4cbfc6b-7e29-49d5-bfee-b625ae4de6a7)
And these are the pods with respective images on my end.
![image](https://github.com/rapidfort/community-images/assets/107160937/c6565bba-7b76-4e37-a9bd-9f168a41a742)

You can also check the pods with image names using this command.
```bash
kubectl get pods -n argocd \
  -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | \
column -t
```

Make sure you are cleaning up in correct way. and pods are present in namespace with "Running" status.

**Comment by Kirandeep-Singh-Khehra** [comment] 2024-05-24 08:03
@rinkydevi It is working with autosync too.

Closing because RapidFort's ArdgoCD image was not used in deployment.

**Closed by Kirandeep-Singh-Khehra** 2024-05-24 08:03 UTC
Labels: bug
